### ISSUE TITLE
Compatibility Question

### ISSUE THREAD

**Issue by j0xhn** [1Hive/evmcrispr#16]
Does this only work inside of the Aragon ecosystem?  Or is this possible to work independently as a way for a proposal to call any function on an EVM compliant chain -- which would be freaking sweet.  If not, would be curious if the team would be interested in helping me expand its functionality to do so?

**Comment by sembrestels** [comment]
It definitely is the objective of the project. Right now it's only compatible with aragon, but we will expand it to evm calls, and also adapt it to gnosis safe. I will update this issue when we offer more compatibility,
