### ISSUE TITLE
unrecognized command

### ISSUE THREAD

**Issue by ZiedChekir** [1Hive/evmcrispr#17]
im trying to access execute a vote through the agent app in aragon in my dao but I get this error 

> evmcl.ts:72 Uncaught (in promise) Error: Unrecognized command: connect
    at evmcl.ts:72:1
    at Array.map (<anonymous>)
    at evmcl.ts:39:1
    at EVMcrispr.encode (EVMcrispr.ts:397:1)
    at aragon (CreateFlow.js:25:1)

here is my code 

` const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = await provider.getSigner();
    const daoAddress = "0x2ec24463ed9BC8122F2b19b313AD8F8d0E99CBB7";
    const evmcrispr = await EVMcrispr.create(daoAddress,signer );
    await evmcrispr.encode(
      evmcl
`
        connect 0x2ec24463ed9BC8122F2b19b313AD8F8d0E99CBB7 token-manager voting
        install agent:new
        grant voting agent:new-agent TRANSFER_ROLE voting100e18
`
    
);`
do you know how can I  fix it ?

**Comment by sembrestels** [comment]
The `connect` command is not part yet of evmcl. The current code would be:
```js
const provider = new ethers.providers.Web3Provider(window.ethereum);
const signer = await provider.getSigner();
const daoAddress = "0x2ec24463ed9BC8122F2b19b313AD8F8d0E99CBB7";
const evmcrispr = await EVMcrispr.create(daoAddress, signer);
await evmcrispr.encode(
  evmcl`
    install agent:new
    grant voting agent:new-agent TRANSFER_ROLE voting
  `,
  ['token-manager', 'voting']
)
```
The EVMcrispr API will be subject to changes in the foreseeable future, as it is alpha code yet. Please feel free to ping us in the [Blossom Labs discord](https://discord.gg/fmqrqhkjHY) if you have any more doubt.
