### ISSUE TITLE
consecutive txs to create agents produces unexecutable votes

### ISSUE THREAD

**Issue by divine-comedian** [1Hive/EVMcrispr#6]
using evmcrispr terminal on xDAI

I have my DAO already setup on xDAI and I ran this code multiple times in an attempt to create multiple agents (I now realize this is not the proper syntax) : 

```
connect <DAO> token-manager voting
install agent:new-agent 
grant . . . EXECUTE_ROLE
grant . . . TRANSFER_ROLE
```
I ran this 3 times and was able to execute all 3 transactions, producing 3 identical votes on my DAO 

![image](https://user-images.githubusercontent.com/67759413/138464346-f3f09836-e65f-492f-9aba-e992355e835a.png)

I was able to enact the first vote no problem but the other two I cannot enact, I get an error saying I do not have permissions. 

![image](https://user-images.githubusercontent.com/67759413/138464689-23e6b3e5-f2fa-4757-96cf-5a2d841203c7.png)

**Comment by sembrestels** [comment]
This is the expected behavior, as only one of those votes should pass because they are trying to install the same agent. If you want to install many agents, you can do it in just one vote.
